### ISSUE TITLE
App 클래스의 navigateUP함수와 refresh함수에 기능 추가 요망

### ISSUE THREAD

**Issue by polarpolar914** [Kredsya/fileexplorer-git-extension#20]
if self.is_gitrepo(self.currentDir):
            os.chdir(self.currentDir)
            statuses_str = os.popen("git status").read()
            git_statuses = parse_git_status(statuses_str)
            self.git_status_column_update(self.currentDir, git_statuses)

위 코드와 같이 현재 경로에서 git status 명령을 실행하고 실행 결과를 표시하는 작업을 추가하여야 함

**Comment by Kredsya** [comment]
complete
