### ISSUE TITLE
onDoubleClick함수 부분 수정 필요

### ISSUE THREAD

**Issue by polarpolar914** [Kredsya/fileexplorer-git-extension#8]
폴더를 더블클릭 하였을때 해당폴더가 깃 레포이면 git status를 실행하여 Git Status 열의 내용들을 업데이트 하는 식으로 처리하고자 함.

현재 master에 머지된 내용은 onDoubleClick함수에서 git status명령을 실행한 결과를 저장한 이후 해당 내용을 분석 하지 않고 Git Status 열의 내용들은 무조건 message로 출력되게 해둔 상태임.

**Comment by Kredsya** [comment]
complete
